"""Search intent and plan models."""

from pydantic import BaseModel, Field


class SearchIntent(BaseModel):
    """Structured user intent extracted by Intent Agent."""

    objective: str = Field(description="Core objective of the search")
    signal_type: str = Field(default="hiring", description="Target signal category, e.g. hiring, expansion")
    target_roles: list[str] = Field(default_factory=list, description="Target job roles or titles")
    target_industries: list[str] = Field(default_factory=list, description="Target industry sectors")
    geographies: list[str] = Field(default_factory=list, description="Target locations or countries")
    target_company_sizes: list[str] = Field(default_factory=list, description="Target company size buckets")
    target_seniority: list[str] = Field(default_factory=list, description="Target role seniority levels")
    freshness_days: int = Field(default=7, ge=1, le=90, description="Freshness window in days")
    decision_maker_types: list[str] = Field(
        default_factory=list, description="Stakeholder types of interest (CTO, VP Eng, Founder, Head of Talent)"
    )
    required_terms: list[str] = Field(default_factory=list, description="Terms that must be present")
    excluded_terms: list[str] = Field(default_factory=list, description="Negative keywords or exclusions")


class SearchPlan(BaseModel):
    """Search plan generated by Query Expansion Agent."""

    queries: list[str] = Field(
        default_factory=list,
        description="List of search queries generated across query families",
    )
    company_identifiers: list[str] = Field(
        default_factory=list,
        description="Public company handles or domain slugs if company-targeted",
    )
    max_queries: int = Field(default=20, ge=1, le=50, description="Maximum number of queries to execute")
    rationale: str = Field(default="", description="Strategic rationale for the generated search plan")


class ActorSearchInput(BaseModel):
    """Validated input model for Apify LinkedIn Post Search Scraper."""

    searchQueries: list[str] = Field(..., min_length=1, max_length=50)
    authorsCompanyPublicIdentifiers: list[str] = Field(default_factory=list)
    maxPosts: int = Field(default=20, ge=1, le=100)
    postedLimit: str = Field(default="week")
    sortBy: str = Field(default="date")
    maxResults: int = Field(default=100, ge=1, le=500)
